/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package un14.oop.lestat;

import un14.oop.olivier.MainMenuGUI;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.io.BufferedWriter;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.IOException;
/**
 *InformationGUI.java
 * @author Lestat Azariel Alvarez Quintana Ordiz
 */
public class InformationGUI extends javax.swing.JFrame {
    //I use this array to save and store the emails that are getting inputted
    private final ArrayList<String> newsletterSubs = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InformationGUI.class.getName());
    private int image = 0; //This is the index that I use to display the slides. I did them with canva.
    //This array has all the slides filepath, and ill use it to select and display. (Goes from 0 to 5)
    private final String[] informationSlides = {
     "/un14/oop/images/information/1.png",
     "/un14/oop/images/information/2.png",
     "/un14/oop/images/information/3.png",
     "/un14/oop/images/information/4.png",
     "/un14/oop/images/information/5.png",
     "/un14/oop/images/information/6.png"
    };
    //This is the file where my email addresses get stored. If the file doesnt exist it will also create one.
    private final String textFile = "newsletterSubscribers.txt";
    //At the start I only printed message but was temporarly, as soon as you changed menu or closed the app the information goes missing. Oli reminded me that we did see how to save them on files, so here im doing the loading the data and the saving the data.
    private void emailReader(){ // The data from the file from previous uses gets loaded here. It also uses catch to avoid crashes in case that the file doesnt exist or was deleted.
        try(BufferedReader reader = new BufferedReader(new FileReader(textFile))){
            String l;
            while ((l = reader.readLine()) !=null){
                newsletterSubs.add(l.trim()); //Using trim so it removes any spaces that might have been done after writing the email.
            }
        }catch (IOException e){
            System.out.println("There is no subscribers file.");
        }
    }
    //This is the writer, this stores the new "subscribers" emails in the file.
    private void emailWriter(){
        try(BufferedWriter writer = new BufferedWriter(new FileWriter(textFile))){
            for (String email : newsletterSubs){
                writer.write(email);
                writer.newLine();
            }
        }catch (IOException e){
            e.printStackTrace();
        }
    }
    //This is how the pictures are showned depending on the number that the index is on, at the start is 0 and thats my "opening slide" that will be displayed all the time. When you use the buttons the index changes and the picture changes with it. It also resizes the picture so its not cut off.
    private void choosingImage(){
       ImageIcon i = new ImageIcon(
       new ImageIcon(getClass().getResource(informationSlides[image])).getImage().getScaledInstance(slides.getWidth(), slides.getHeight(), Image.SCALE_SMOOTH));
       
       slides.setIcon(i);
    }
    
    
    //Creates new form InformationGUI
     
    public InformationGUI() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        choosingImage(); //This is so the slides start showing from the moment you go in to the menu, to avoid having an empty label. It will start on the opening slide
        emailReader();//This is so it loads the emails from the file when accessing this menu.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuButton = new javax.swing.JButton();
        goLeft = new javax.swing.JButton();
        goRight = new javax.swing.JButton();
        slides = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        subscribe = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        verify = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMenuButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MainMenuButton.setText("Main Menu");
        MainMenuButton.addActionListener(this::MainMenuButtonActionPerformed);
        getContentPane().add(MainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        goLeft.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        goLeft.setText("<");
        goLeft.addActionListener(this::goLeftActionPerformed);
        getContentPane().add(goLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, 70));

        goRight.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        goRight.setText(">");
        goRight.addActionListener(this::goRightActionPerformed);
        getContentPane().add(goRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 300, -1, 70));

        slides.setText("jLabel2");
        getContentPane().add(slides, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 86, 730, 480));

        email.setText("example@gmail.com");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 270, 30));

        subscribe.setText("Add Subscription");
        subscribe.addActionListener(this::subscribeActionPerformed);
        getContentPane().add(subscribe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 670, -1, -1));

        cancel.setText("Cancel Subscription");
        cancel.addActionListener(this::cancelActionPerformed);
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 670, -1, -1));

        verify.setText("Verify Subscription");
        verify.addActionListener(this::verifyActionPerformed);
        getContentPane().add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, -1, -1));

        jLabel2.setText("Subscribe to the Newsletter");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/un14/oop/images/InformationBG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//This is my first button, goes to the left by changing the index.
    private void goLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goLeftActionPerformed
        if (image == 0){ //Im using a conditional so the program doesnt keep increasing the index and loops around keeping a "smooth" transitions between the slides.
            image = 5;
            choosingImage();
        }else{
            image -= 1;
        }
        choosingImage();
    }//GEN-LAST:event_goLeftActionPerformed
//same as before but to the right.
    private void goRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goRightActionPerformed
        if (image == 5){
            image = 0;
            choosingImage();
        }else{
            image += 1;
        }
        choosingImage();
    }//GEN-LAST:event_goRightActionPerformed
//This was added by oli that was in charge of the main funcionallity of the GUI, He created the files and loaded the bacground labels. In the git you will see that he created the menues and connected them. But the rest of the functionallity of this menu i did it.
    private void MainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuButtonActionPerformed
        // TODO add your handling code here:
        MainMenuGUI myGUI = new MainMenuGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuButtonActionPerformed
//This is my validator, im making sure that has some of the main components of a mail address, and avoiding empty submitions.
    private boolean validation(String val){
        return val != null && val.contains("@") && val.contains(".");
    }
//This one checks and displays that your "subscription" was canceled or that it wasnt subscribed. It removes it from the file.    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        String val = email.getText().trim();
        
        if(newsletterSubs.remove(val)){
            emailWriter();
            JOptionPane.showMessageDialog(this, "The email " + val + " has been unsubscribed");
        }else{
                        JOptionPane.showMessageDialog(this, "The email "+ val +" was not subscribed");
        }
    }//GEN-LAST:event_cancelActionPerformed
//Here I use the validator, if the email is not valid will give an alert. If that email is already in the array of emails will also give an alert. And lastly it will add the item to the array and the file.
    private void subscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeActionPerformed
        String val = email.getText().trim();
        
        if (!validation(val)){
            JOptionPane.showMessageDialog(this, "The email you entered is not valid");
        }else if (newsletterSubs.contains(val)){
            JOptionPane.showMessageDialog(this, "You already are subscribed with this email.");
        }else{
            newsletterSubs.add(val);
            emailWriter();
            JOptionPane.showMessageDialog(this, "Thank you for subscribing");
        }
    }//GEN-LAST:event_subscribeActionPerformed
//This is to search an email and find out if it was subscribed or not. Because this is an app "for the public" having very easily exposed all the emails would be a risk. SO they can search if they already know what they are searching.
    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
        String val = email.getText().trim();
        
        if(newsletterSubs.contains(val)){
            JOptionPane.showMessageDialog(this, val  + " is subscribed.");
        }else{
            JOptionPane.showMessageDialog(this, val  + " is not subscribed.");
        }
    }//GEN-LAST:event_verifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InformationGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField email;
    private javax.swing.JButton goLeft;
    private javax.swing.JButton goRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel slides;
    private javax.swing.JButton subscribe;
    private javax.swing.JButton verify;
    // End of variables declaration//GEN-END:variables
}
