/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package un14.oop;

/**
 *
 * @author Olivier Nowak 
 */
public class GameMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameMenuGUI.class.getName());

    /**
     * Creates new form GameMenuGUI
     */
    public GameMenuGUI() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        crabGame = new javax.swing.JRadioButton();
        shrimpGame = new javax.swing.JRadioButton();
        fishingGame = new javax.swing.JRadioButton();
        MainMenuButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(crabGame);
        crabGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        crabGame.setText("Crab Game");
        crabGame.setToolTipText("");
        getContentPane().add(crabGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 170, 40));

        buttonGroup1.add(shrimpGame);
        shrimpGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        shrimpGame.setText("Shrimp Game");
        getContentPane().add(shrimpGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        buttonGroup1.add(fishingGame);
        fishingGame.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fishingGame.setText("Fishing Game");
        getContentPane().add(fishingGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, -1, -1));

        MainMenuButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MainMenuButton.setText("Main Menu");
        MainMenuButton.addActionListener(this::MainMenuButtonActionPerformed);
        getContentPane().add(MainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        PlayButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PlayButton.setText("Play");
        PlayButton.addActionListener(this::PlayButtonActionPerformed);
        getContentPane().add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 150, 60));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 150, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Select Desired Game");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 230, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Insert Player Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 210, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/un14/oop/images/GameMenuBG.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel4.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel4.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuButtonActionPerformed
        // TODO add your handling code here:
        MainMenuGUI myGUI = new MainMenuGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuButtonActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        if(crabGame.isSelected()){
           CrabApp.main(null);
           this.dispose();
        }
        if(shrimpGame.isSelected()){
           //YKShrimpApp.main(null); commented as its missing its main right now
           this.dispose();
        }
        if(fishingGame.isSelected()){
           FishingApp.main(null);
           this.dispose();
        }
    }//GEN-LAST:event_PlayButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton crabGame;
    private javax.swing.JRadioButton fishingGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton shrimpGame;
    // End of variables declaration//GEN-END:variables
}
