/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package un14.oop;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Lestat Azariel Alvarez Quintana Ordiz
 */
public class InformationGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InformationGUI.class.getName());
    private int image = 0;
    private final String[] informationSlides = {
     "/un14/oop/images/information/1.png",
     "/un14/oop/images/information/2.png",
     "/un14/oop/images/information/3.png",
     "/un14/oop/images/information/4.png",
     "/un14/oop/images/information/5.png",
     "/un14/oop/images/information/6.png"
    };
       
    private void choosingImage(){
       ImageIcon i = new ImageIcon(
       new ImageIcon(getClass().getResource(informationSlides[image])).getImage().getScaledInstance(slides.getWidth(), slides.getHeight(), Image.SCALE_SMOOTH));
       
       slides.setIcon(i);
    }
    
    
    //Creates new form InformationGUI
     
    public InformationGUI() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        //choosingImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenuButton = new javax.swing.JButton();
        goLeft = new javax.swing.JButton();
        goRight = new javax.swing.JButton();
        slides = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMenuButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MainMenuButton.setText("Main Menu");
        MainMenuButton.addActionListener(this::MainMenuButtonActionPerformed);
        getContentPane().add(MainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        goLeft.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        goLeft.setText("<");
        goLeft.addActionListener(this::goLeftActionPerformed);
        getContentPane().add(goLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, -1, 70));

        goRight.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        goRight.setText(">");
        goRight.addActionListener(this::goRightActionPerformed);
        getContentPane().add(goRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, -1, 70));

        slides.setIcon(new javax.swing.ImageIcon(getClass().getResource("/un14/oop/images/information/LabelIcon.png"))); // NOI18N
        slides.setText("jLabel2");
        getContentPane().add(slides, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 86, 730, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/un14/oop/images/InformationBG.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goLeftActionPerformed
        image -= 1;
        choosingImage();
    }//GEN-LAST:event_goLeftActionPerformed

    private void goRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goRightActionPerformed
        image += 1;
        choosingImage();
    }//GEN-LAST:event_goRightActionPerformed

    private void MainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuButtonActionPerformed
        // TODO add your handling code here:
        MainMenuGUI myGUI = new MainMenuGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MainMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InformationGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JButton goLeft;
    private javax.swing.JButton goRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel slides;
    // End of variables declaration//GEN-END:variables
}
