/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package un14.oop;

/**
 *
 * @author candy
 */
public class MainMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuGUI.class.getName());

    /**
     * Creates new form MainMenuGUI
     */
    public MainMenuGUI() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SettingsButton = new javax.swing.JButton();
        GamesButton = new javax.swing.JButton();
        InformationButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SettingsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SettingsButton.setText("Settings");
        SettingsButton.addActionListener(this::SettingsButtonActionPerformed);
        getContentPane().add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 160, -1));

        GamesButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        GamesButton.setText("Games");
        GamesButton.addActionListener(this::GamesButtonActionPerformed);
        getContentPane().add(GamesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 160, -1));

        InformationButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        InformationButton.setText("Information");
        InformationButton.addActionListener(this::InformationButtonActionPerformed);
        getContentPane().add(InformationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Main Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Life Below Water");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/un14/oop/images/MainMenuBG.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel3.setMinimumSize(new java.awt.Dimension(1280, 720));
        jLabel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        // TODO add your handling code here:
        SettingsGUI myGUI = new SettingsGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void InformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationButtonActionPerformed
        // TODO add your handling code here:
        InformationGUI myGUI = new InformationGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InformationButtonActionPerformed

    private void GamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesButtonActionPerformed
        // TODO add your handling code here:
        GameMenuGUI myGUI = new GameMenuGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GamesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GamesButton;
    private javax.swing.JButton InformationButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
